### ISSUE TITLE
Suggestie: kleurenschaal (voorwaardelijke opmaak) toevoegen

### ISSUE THREAD

**Issue by dennisenderink** [GvY85/FO-calculators#1]
Voor de overzichtelijkheid lijkt het mij handig om aan de "Opbrengsten" tabel voor ieder jaar voorwaardelijke opmaak toe te voegen. Zie bijlage.

[Kosten.vergelijking.BND.Meesman.Rabo.ABN.ING.BINCK.v2.5-kleurenschaal.xlsx](https://github.com/GvY85/FO-calculators/files/4055714/Kosten.vergelijking.BND.Meesman.Rabo.ABN.ING.BINCK.v2.5-kleurenschaal.xlsx)

**Comment by dennisenderink** [comment]
Versie 2.6 bijgewerkt.

[Kosten.vergelijking.BND.Meesman.Rabo.ABN.ING.BINCK.v2.6-kleurenschaal.xlsx](https://github.com/GvY85/FO-calculators/files/4055719/Kosten.vergelijking.BND.Meesman.Rabo.ABN.ING.BINCK.v2.6-kleurenschaal.xlsx)

**Comment by GvY85** [comment]
Done :)
