### ISSUE TITLE
Suggestie: mogelijkheid voor startkapitaal

### ISSUE THREAD

**Issue by hansem72** [GvY85/FO-calculators#2]
Handig als je bijvoorbeeld overstapt en wil vergelijken.

**Comment by GvY85** [comment]
Done :)

**Comment by hansem72** [comment]
Top!! Thx.

Groeten,
Marco

**Comment by hansem72** [comment]
Ik zie de mogelijkheid nog niet in 2.8, kijk ik verkeerd?

**Comment by hansem72** [comment]
Is deze functionaliteit er al, ik zie het niet in 2.9 of 2.8.
